### ISSUE TITLE
"Uncaught ReferenceError: regeneratorRuntime is not defined"

### ISSUE THREAD

**Issue by jnaviask** [luniehq/cosmos-api#2]
I'm trying to use the API in a project built on webpack, and I get this error at runtime (build is performed successfully). I've tried a lot of the proposed solutions through Googling and none were able to resolve this issue. Any ideas? Is there a specific babel module I need to include at the right place? Thanks!

**Comment by faboweb** [comment]
How do you integrate the library? Can you share a repo?

**Comment by jnaviask** [comment]
Unfortunately it's a private repo, but I added with yarn and I'm doing an identical include of the query-only API as in the README. We're using webpack, babel, typescript for the project, here's our babelrc:

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": "2"
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-async-generator-functions"
  ]
}
```

Please let me know if there's any other files or details I can share that might help diagnose the issue.

**Comment by faboweb** [comment]
I would need to investigate more. As a quick fix you can just import the actual `src/index.js`. Then your babel should kick in and work like the rest of your code.

**Comment by jnaviask** [comment]
Great, the workaround was successful. I'll use it like this for now!

**Comment by okwme** [comment]
I'm getting this error when trying to access with require (can't use import) 
```javascript
const Cosmos = require('@lunie/cosmos-js')
```

**Comment by okwme** [comment]
I don't get that error if i import directly like mentioned:
```js
const Cosmos = require('../node_modules/@lunie/cosmos-js/src/index.js').default
```
Although I get an error on:
```js
  const cosmos = Cosmos(restEndpoint, cosmosAddress)
```
which says:
```sh
Function invocation failed: TypeError: Class constructor _ cannot be invoked without 'new'
```
probably because i'm not using babel?
Shouldn't I be able to import the library as vanilla js?
