### ISSUE TITLE
The examples seem outdated. Would appreciate if someone could update them.

### ISSUE THREAD

**Issue by yzhanginwa** [luniehq/cosmos-api#22]
The examples seem outdated. Would appreciate if someone could update them. Thanks!

**Comment by jbibla** [comment]
hey @yzhanginwa are there particular examples that are no longer correct?

**Comment by shrpne** [comment]
Looks like this from README is not valid JS
```js
const signMessage = createSignedTransaction({ gas: 1000, gasPrices = [{ amount: "10", denom: "uatom" }], memo = `Hi from Lunie` }, [sendMsg], signer, chainId: "test-chain", accountNumber: 0, sequence: 12);
```

**Comment by jbibla** [comment]
we would recommend using https://github.com/cosmos/cosmjs
