### ISSUE TITLE
RPC Subscribe

### ISSUE THREAD

**Issue by jnaviask** [luniehq/cosmos-api#5]
Hi, I was wondering if there were plans to support RPC subscriptions, so that we can obtain real-time block header and TX data. Currently I'm using https://github.com/nomic-io/js-tendermint + https://github.com/cosmos/amino-js to do this (and am using this library as an RPC query/tx wrapper), but it would be nice to have a single library solution. Please let me know if this feature is feasible, thanks!

**Comment by faboweb** [comment]
I agree that this would be nice. We used `js-tendermint` before and in Lunie we currently use only a part of it.
What would be the use cases you want to use RPC subscriptions for? I might add something to this library to facilitate this.

**Comment by jnaviask** [comment]
My major use cases are:
1. I want block heights and timestamps (for internal state)
2. I want streaming transactions (to display for users)
3. It would be cool if I could also get, say, streaming balance updates, but I couldn't figure out how to do this using the current API
