### ISSUE TITLE
Support send with offline signature.

### ISSUE THREAD

**Issue by jnaviask** [luniehq/cosmos-api#7]
Currently there is no way to easily perform the following workflow:
1. Generate a transaction without a signature.
2. Create a signature from the transaction via command line (offline).
3. Construct the signed transaction.
4. Broadcast the signed transaction.

Steps 1-3 are more or less doable, but there's no function to send a transaction signed offline.

The most obvious solution would be to refactor this piece into a separate "broadcastSignedTx()" function: https://github.com/luniehq/cosmos-api/blob/develop/src/send.js#L11 I can submit a PR if that would help. Thanks!

**Comment by faboweb** [comment]
Hey! Sorry for the long delay. Simplest solution is to create an `offlineSigner` (`() => ({ publicKey, signature })`) function which just returns the signature. This then can be used in the `send` function (https://github.com/luniehq/cosmos-api/blob/develop/src/send.js#L7).

**Comment by faboweb** [comment]
I am open to see your helper function if you think it will provide value!

**Comment by faboweb** [comment]
Another question: If you are using the CLI to sign, why are you not using the CLI for generation of the tx and broadcasting it?

**Comment by jnaviask** [comment]
> Another question: If you are using the CLI to sign, why are you not using the CLI for generation of the tx and broadcasting it?

I'll look into whether that makes sense for us -- we're building a front-end, and I assumed we'd want to do as much as possible on it, but it may also make sense to direct users to the CLI for the entire transaction.
